# Generated by Django 4.2.1 on 2023-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsdetailpage",
            name="highlight",
            field=models.BooleanField(
                default=True,
                help_text="Wyświetl wprowadzaną aktualność jako pierwszą informację na głównej\n        stronie.",
                verbose_name="Wyróżnienie na stronie głównej",
            ),
        ),
    ]
