# Generated by Django 4.2.1 on 2023-08-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_contactpage_alt_attr_and_more"),
        ("news", "0002_alter_newsdetailpage_highlight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="minigalleryimage",
            name="alt_attr",
        ),
        migrations.RemoveField(
            model_name="newsdetailpage",
            name="alt_attr",
        ),
        migrations.AlterField(
            model_name="newsdetailpage",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.categorysnippet",
                verbose_name="Kategoria",
            ),
        ),
    ]
