# Generated by Django 4.2.1 on 2023-10-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newsdetailpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minigalleryimage",
            name="alt_attr",
            field=models.CharField(
                blank=True,
                help_text="Opis tekstowy zdjęcia (najczęściej od 5 do 15 słów).",
                max_length=255,
                verbose_name="Opis alternatywny",
            ),
        ),
        migrations.AlterField(
            model_name="newsdetailpage",
            name="alt_attr",
            field=models.CharField(
                blank=True,
                help_text="Opisz co przedstawia zdjęcie główne. Pole nie powinno być puste\n        (wymóg dostępności stron internetowych instytucji publicznych.)",
                max_length=255,
                verbose_name="Opis alternatywny",
            ),
        ),
    ]
