# Generated by Django 4.2.1 on 2023-10-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_luckynumbersnippet_options"),
        ("news", "0005_alter_minigalleryimage_alt_attr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsdetailpage",
            name="banner_image",
            field=models.ForeignKey(
                help_text="Preferowana orientacja pozioma. Pamiętaj, że tekst zamieszczony\n            na zdjęciu jest niedostępny i powinien znaleźć się również w treści\n            artykułu (wymóg dostępności stron internetowych instytucji publicznych.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.customimage",
                verbose_name="Zdjęcie główne",
            ),
        ),
    ]
