# Generated by Django 4.2.1 on 2024-03-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_ordinarypage_content"),
        ("news", "0013_alter_minigalleryimage_alt_attr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsdetailpage",
            name="banner_image",
            field=models.ForeignKey(
                help_text="Preferowana orientacja pozioma.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.customimage",
                verbose_name="Zdjęcie główne",
            ),
        ),
    ]
