# Generated by Django 4.2.1 on 2023-08-28 10:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0084_query_alter_page_title_searchpromotion_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityInfoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=250, verbose_name="Nazwa podmiotu"),
                ),
                ("web_url", models.URLField(verbose_name="Adres strony internetowej")),
                (
                    "publication_date",
                    models.DateField(
                        verbose_name="Data publikacji strony internetowej"
                    ),
                ),
                (
                    "update_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data ostatniej istotnej aktualizacji",
                    ),
                ),
                ("accordance", models.BooleanField(verbose_name="Zgodność z ustawą")),
                (
                    "exceptions",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Wypełnij w przypadku częściowej zgodności z ustawą",
                        null=True,
                        verbose_name="Niezgodności z ustawą, wyłączenia",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(verbose_name="Data sporządzenia deklaracji"),
                ),
                (
                    "review_date",
                    models.DateField(
                        verbose_name="Data ostatniego przeglądu deklaracji"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="Osoba do kontaktu"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Telefon")),
                (
                    "architecture_desc",
                    wagtail.fields.RichTextField(
                        verbose_name="Opis dostępności architektonicznej"
                    ),
                ),
                (
                    "contact_methods",
                    wagtail.fields.RichTextField(
                        blank=True,
                        null=True,
                        verbose_name="Komunikacja dla osób niesłyszących lub słabo słyszących",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deklaracja dostępności",
            },
            bases=("wagtailcore.page",),
        ),
    ]
