# Generated by Django 4.2.1 on 2023-08-29 05:09

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_accessibilityinfopage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilityinfopage",
            name="accordance",
            field=models.BooleanField(default=True, verbose_name="Zgodność z ustawą"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfopage",
            name="contact_methods",
            field=wagtail.fields.RichTextField(
                blank=True,
                null=True,
                verbose_name="Informacja o dostępności tłumacza języka migowego.",
            ),
        ),
    ]
