# Generated by Django 4.2.1 on 2023-08-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_accessibilityinfopage_accordance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="alt_attr",
        ),
        migrations.RemoveField(
            model_name="teacherspage",
            name="alt_attr",
        ),
        migrations.AddField(
            model_name="customimage",
            name="alt_attr",
            field=models.CharField(
                blank=True,
                help_text="Opis tekstowy zdjęcia głównego (najczęściej od 5 do 15 słów) mający\n        na celu umożliwienie przekazu treści osobom słabowidzącym.",
                max_length=255,
                null=True,
                verbose_name="Opis alternatywny",
            ),
        ),
    ]
