# Generated by Django 4.2.1 on 2023-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_schoolyearsnippet_delete_newscategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=25, verbose_name="nazwa kategorii"),
                ),
                (
                    "color",
                    models.IntegerField(
                        choices=[
                            (0, "różowy"),
                            (1, "niebieski"),
                            (2, "zielony"),
                            (3, "brązowy"),
                            (4, "pomarańczowy"),
                        ],
                        default=0,
                        verbose_name="Kolor powiązany z kategorią",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria1",
                "verbose_name_plural": "Kategorie",
                "ordering": ["name"],
            },
        ),
    ]
