# Generated by Django 4.2.1 on 2023-10-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_luckynumbersnippet_alter_ordinarypage_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="luckynumbersnippet",
            options={
                "verbose_name": "Niepytany numerek",
                "verbose_name_plural": "Niepytany numerek",
            },
        ),
    ]
