# Generated by Django 4.2.1 on 2023-07-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_categorysnippet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorysnippet",
            options={
                "ordering": ["name"],
                "verbose_name": "Kategoria",
                "verbose_name_plural": "Kategorie",
            },
        ),
    ]
