# Generated by Django 4.2.1 on 2025-07-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0090_merge_20231002_1822"),
        ("core", "0008_alter_ordinarypage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ESchoolSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(blank=True, verbose_name="Link zewnętrzny"),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Link do podstrony",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link do e-szkoły",
            },
        ),
    ]
