# Generated by Django 4.2.1 on 2023-08-26 14:26

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0085_query_searchpromotion_querydailyhits"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "main_text",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Opis galerii"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Data publikacji wyświetlana na stronie.",
                        null=True,
                        verbose_name="Data publikacji",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Podaj autora, jeśli chcesz żeby ta informacja była wyświetlona\n            na stronie",
                        max_length=80,
                        null=True,
                        verbose_name="autor",
                    ),
                ),
                (
                    "on_main_page",
                    models.BooleanField(
                        default=True,
                        help_text="Pole pozostaw puste np. jeśli o wydarzeniu z galerii został\n        opublikowany osobny\n        artykuł w aktualnościach. Dzięki temu informacja o wydarzeniu nie pojawi się\n        na stronie głównej dwukrotnie.",
                        verbose_name="Wyświetl na głównej stronie w Najnowszych wpisach",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=core.models.CategorySnippet.get_default_id,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.categorysnippet",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.schoolyearsnippet",
                        verbose_name="Rok szkolny",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeria zdjęć",
                "verbose_name_plural": "Galerie zdjęć",
            },
            bases=(core.models.PagePaginationMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="GalleryIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista galerii zdjęć",
            },
            bases=(
                core.models.PagePaginationMixin,
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "alt_attr",
                    models.CharField(
                        blank=True,
                        help_text="Opis tekstowy zdjęcia (najczęściej od 5 do 15 słów) mający\n        na celu m.in. umożliwienie przekazu treści osobom słabowidzącym.",
                        max_length=255,
                        verbose_name="Opis alternatywny",
                    ),
                ),
                (
                    "highlight",
                    models.BooleanField(
                        default=False,
                        help_text="Wybrane zdjęcie będzie wyświetlone w wizytówce galerii",
                        verbose_name="Zdjęcie główne",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.customimage",
                        verbose_name="",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="gallery.gallerydetailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
