# Generated by Django 4.2.1 on 2023-10-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="alt_attr",
            field=models.CharField(
                blank=True,
                help_text="Opis tekstowy zdjęcia. Zadbaj o to,\n        żeby co najmniej dla zdjęcia głównego to pole nie pozostało puste.",
                max_length=255,
                verbose_name="Opis alternatywny",
            ),
        ),
    ]
