# Generated by Django 4.2.1 on 2023-08-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryimage",
            name="alt_attr",
        ),
    ]
