# Generated by Django 4.2.1 on 2023-06-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_blogpage_blogpagegalleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpagegalleryimage",
            name="alt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
