# Generated by Django 4.2.1 on 2023-06-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_blogpagegalleryimage_alt"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="galleryimage",
        #     name="image",
        # ),
        # migrations.RemoveField(
        #     model_name="galleryimage",
        #     name="page",
        # ),
        # migrations.RemoveField(
        #     model_name="gallerylistingpage",
        #     name="page_ptr",
        # ),
        migrations.RemoveField(
            model_name="blogpagegalleryimage",
            name="alt",
        ),
        migrations.DeleteModel(
            name="GalleryDetailPage",
        ),
        migrations.DeleteModel(
            name="GalleryImage",
        ),
        migrations.DeleteModel(
            name="GalleryListingPage",
        ),
    ]
