# Generated by Django 4.2.1 on 2023-06-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("gallery", "0005_gallerydetailpage_galleryimage_galleryindexpage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallerydetailpage",
            options={
                "verbose_name": "Galeria zdjęć",
                "verbose_name_plural": "Galerie zdjęć",
            },
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="alt_attr",
            field=models.CharField(
                blank=True,
                help_text="Opis tekstowy zdjęcia (najczęściej od 5 do 15 słów) mający\n        na celu umożliwienie przekazu treści osobom słabowidzącym.",
                max_length=255,
                verbose_name="Opis alternatywny",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Zdjęcie",
            ),
        ),
    ]
