# Generated by Django 4.2.1 on 2023-06-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("gallery", "0006_alter_gallerydetailpage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerydetailpage",
            name="heading",
        ),
        migrations.AddField(
            model_name="gallerydetailpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Opcjonalny dodatkowy opis galerii.",
                null=True,
                verbose_name="Opis galerii",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="",
            ),
        ),
    ]
