# Generated by Django 4.2.1 on 2023-06-28 16:45

from django.db import migrations, models
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_remove_gallerydetailpage_heading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerydetailpage",
            name="description",
        ),
        migrations.AddField(
            model_name="gallerydetailpage",
            name="main_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Opcjonalny dodatkowy opis galerii.",
                null=True,
                verbose_name="Opis galerii",
            ),
        ),
        migrations.AddField(
            model_name="gallerydetailpage",
            name="publish_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Data publikacji wyświetlana na stronie.",
                null=True,
                verbose_name="Data publikacji",
            ),
        ),
    ]
