# Generated by Django 4.2.1 on 2023-06-28 17:00

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0018_alter_newsdetailpage_publish_date"),
        ("gallery", "0008_remove_gallerydetailpage_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerydetailpage",
            name="category",
            field=models.ForeignKey(
                default=news.models.NewsCategory.get_default_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.newscategory",
            ),
        ),
    ]
