# Generated by Django 4.2.1 on 2023-06-28 17:02

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0018_alter_newsdetailpage_publish_date"),
        ("gallery", "0009_gallerydetailpage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerydetailpage",
            name="category",
            field=models.ForeignKey(
                default=news.models.NewsCategory.get_default_id,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.newscategory",
            ),
        ),
    ]
