# Generated by Django 4.2.1 on 2023-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0010_alter_gallerydetailpage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="highlight",
            field=models.BooleanField(
                default=False,
                help_text="Wybrane zdjęcie będzie wyświetlone w wizytówce galerii",
                verbose_name="Zdjęcie główne",
            ),
        ),
    ]
