# Generated by Django 4.2.1 on 2024-02-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="highlight",
            field=models.BooleanField(
                default=False,
                help_text="Dodaj dodatkowy pomarańczowy cień wokół przycisku, aby był bardziej widoczny podczas rekrutacji.",
                verbose_name="Wyróżnienie przycisku Rekrutacja",
            ),
        ),
    ]
