# Generated by Django 4.2.1 on 2024-03-06 09:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0090_merge_20231002_1822"),
        ("core", "0008_alter_ordinarypage_content"),
        ("home", "0002_homepage_highlight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=70, null=True, verbose_name="Nazwa programu"
                    ),
                ),
                (
                    "bcgimg",
                    models.ForeignKey(
                        help_text="Poziome, szerokość 450px",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.customimage",
                        verbose_name="Zdjęcie w tle",
                    ),
                ),
                (
                    "link_to_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Link do podstrony ze szczegółami programu",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        help_text="Logo - plik PNG z tłem transparentnym lub\n        zwykłe poziome zdjęcie o szerokości 450px",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.customimage",
                        verbose_name="Logo lub główne zdjęcie",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
