# Generated by Django 4.2.1 on 2024-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_programme"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="alt_attr",
            field=models.CharField(
                default="",
                max_length=255,
                null=True,
                verbose_name="Opis alternaywny loga/zdjęcia",
            ),
        ),
    ]
