# Generated by Django 4.2.1 on 2025-07-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_eschoolsnippet"),
        ("home", "0004_programme_alt_attr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="bcgimg",
            field=models.ForeignKey(
                blank=True,
                help_text="Poziome, szerokość 450px",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.customimage",
                verbose_name="Zdjęcie w tle",
            ),
        ),
    ]
